import type { GlossaryTerm } from '$lib/types/glossary';

/** Generated by scripts/import-glossary.mjs — run npm run import:glossary */
export const ghazalTerms: GlossaryTerm[] = [
	{
		"slug": "matla",
		"category": "ghazal",
		"english": {
			"label": "Matlaʿ",
			"definition": "The opening couplet of a ghazal. It sets the rhyme (qāfiya) and the refrain (radeef) when those devices are used."
		},
		"urdu": {
			"label": "qāfiya",
			"definition": "qāfiya · radeef"
		}
	},
	{
		"slug": "radeef",
		"category": "ghazal",
		"english": {
			"label": "Radeef",
			"definition": "A word or short phrase repeated at the end of both lines of every couplet. It follows the rhyme syllables."
		}
	},
	{
		"slug": "kaafiya",
		"category": "ghazal",
		"english": {
			"label": "Kaafiya",
			"definition": "The rhyming portion immediately before the radeef. It must remain consistent across couplets in a classical ghazal."
		},
		"urdu": {
			"label": "radeef",
			"definition": "radeef"
		}
	},
	{
		"slug": "qaafiya",
		"category": "ghazal",
		"english": {
			"label": "Qaafiya",
			"definition": "Another term for the rhyme scheme carried by the kaafiya; editors sometimes distinguish fine points of rhyme quality, but in ordinary use it overlaps with kaafiya."
		},
		"urdu": {
			"label": "kaafiya",
			"definition": "kaafiya · kaafiya"
		}
	},
	{
		"slug": "behr",
		"category": "ghazal",
		"english": {
			"label": "Behr",
			"definition": "The metrical pattern (prosody) governing syllable length and foot division in a line. Urdu meters derive largely from the Arabic–Persian system of ʿarūż."
		}
	},
	{
		"slug": "behr-e-hazaj",
		"category": "ghazal",
		"english": {
			"label": "Behr-e-Hazaj",
			"definition": "A common meter built on the foot مَفَاعِیلُنْ (mafāʿīlun). In classroom notation the repeated pattern is often written as 1–2–2–2 (four feet per miṣraʿ in this analysis). The same foot pattern applies to miṣraʿ ul-ūlā and miṣraʿ uṣ-ṣānī when the line is scanned in four segments."
		},
		"urdu": {
			"label": "miṣraʿ",
			"script": "مَفَاعِیلُنْ",
			"definition": "miṣraʿ · miṣraʿ ul-ūlā · miṣraʿ uṣ-ṣānī"
		}
	},
	{
		"slug": "sher",
		"category": "ghazal",
		"english": {
			"label": "Sher",
			"definition": "A couplet; the ghazal is composed of an uninterrupted sequence of independent couplets sharing meter, rhyme, and refrain."
		}
	},
	{
		"slug": "maqta",
		"category": "ghazal",
		"english": {
			"label": "Maqtaʿ",
			"definition": "The closing couplet, where the poet may insert a takhalluṣ (pen name)."
		},
		"urdu": {
			"label": "takhalluṣ",
			"definition": "takhalluṣ"
		}
	},
	{
		"slug": "misra-ul-ula-misra-us-sani",
		"category": "ghazal",
		"english": {
			"label": "Miṣraʿ ul-ūlā / Miṣraʿ uṣ-ṣānī",
			"definition": "The first and second half-lines of a couplet: the ūlā (“upper”) and ṣānī (“second”) lines. In scansion exercises, each is often marked with the same rhythmic formula (e.g. 1–2–2–2 in Behr-e-Hazaj)."
		},
		"urdu": {
			"label": "ūlā",
			"definition": "ūlā · ṣānī"
		}
	},
	{
		"slug": "aruz-urooz",
		"category": "ghazal",
		"english": {
			"label": "ʿArūż (Urooz)",
			"definition": "The classical system of Arabic–Persian–Urdu prosody; in shorthand notes “urooz” refers to the balance of the couplet—how the two miṣraʿ match in meter and weight."
		},
		"urdu": {
			"label": "miṣraʿ",
			"definition": "miṣraʿ"
		}
	},
	{
		"slug": "majazi",
		"category": "ghazal",
		"english": {
			"label": "Majāzī",
			"definition": "Figurative or “worldly” sense: the image as metaphor, story, or human situation—before the tanzīl (unveiling) of a deeper reading."
		},
		"urdu": {
			"label": "tanzīl",
			"definition": "tanzīl"
		}
	},
	{
		"slug": "haqiqi",
		"category": "ghazal",
		"english": {
			"label": "Ḥaqīqī",
			"definition": "The “real” or spiritual sense: the inward, unseen dimension (often ishq or divine address) that Sufi and classical readers hear beneath the majāzī surface."
		},
		"urdu": {
			"label": "ishq",
			"definition": "ishq · majāzī"
		}
	},
	{
		"slug": "khaliq",
		"category": "ghazal",
		"english": {
			"label": "Khāliq",
			"definition": "The Creator."
		}
	},
	{
		"slug": "makhlooq",
		"category": "ghazal",
		"english": {
			"label": "Makhlooq",
			"definition": "Creation (creatures, the created world)."
		}
	},
	{
		"slug": "tasawwuf",
		"category": "ghazal",
		"english": {
			"label": "Tasawwuf",
			"definition": "Islamic mysticism (Sufism): the path of inward purification, discipline, and love-centered knowledge of God. In poetry, Sufi registers often overlap with ḥaqīqī meaning, not only majāzī romance."
		},
		"urdu": {
			"label": "ḥaqīqī",
			"definition": "ḥaqīqī · majāzī"
		}
	},
	{
		"slug": "behr-hazaj",
		"category": "topic",
		"english": {
			"label": "Behr-e-Hazaj: pattern",
			"definition": "Below is a line-by-line scansion (taqṭīʿ) with rhythmic weighting as in the notes supplied. The ghazal is often counted as nine couplets; here the material is divided into ten blocks because two consecutive couplets were analyzed separately (former items 6 and 7 in the original notes)."
		}
	}
];
